# Overall config
title: xpcoffee
author: Rick Bosch
description: >- 
  ☕ ⌨️ ⚙️
baseurl: ""
main_image: https://xpcoffee.github.io/assets/xpcoffee.png
url: "https://xpcoffee.github.io"
social:
  twitter: explodedcoffee
  github:  xpcoffee
  linkedin: emerickbosch
  email: xpc.dev@gmail.com

markdown: kramdown

theme: minima
plugins:
  - jekyll-feed