# Overall config
title: xpcoffee
email: xpc.dev@gmail.com
description: >- 
  ☕ ⌨️ ⚙️
baseurl: ""
main_image: https://xpcoffee.github.io/assets/xpcoffee.png
url: "https://xpcoffee.github.io"
twitter_username: explodedcoffee
github_username:  xpcoffee
linkedin_username: emerickbosch

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: minima
plugins:
  - jekyll-feed