# Overall config
title: xpcoffee
email: xpc.dev@gmail.com
description: >- 
  *shrug*
baseurl: ""
url: "https://xpcoffee.github.io"
twitter_username: xpcoffee
github_username:  xpcoffee

# Build config
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed