# Overall config
title: xpcoffee
author: Rick Bosch
description: >- 
  ☕ ⌨️ ⚙️
baseurl: ""
main_image: https://xpcoffee.github.io/assets/xpcoffee.png
url: "https://xpcoffee.github.io"
social:
  twitter: explodedcoffee
  github:  xpcoffee
  linkedin: emerickbosch
  email: xpc.dev@gmail.com

theme: minima
plugins:
  - jekyll-feed

# Can't currently disable the rouge highlighter in GitHub pages. Re-disable once we can.
# https://docs.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-highlighter-language
# highlighter: none

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
