# Overall config
title: xpcoffee
email: xpc.dev@gmail.com
description: >- 
      )  (
     (   ) )
      ) ( (
    _(_____)_
 .-'---------|  
| /|         |
| \|         |
 '-'_________'
    '-------'
baseurl: ""
url: "https://xpcoffee.github.io"
twitter_username: xpcoffee
github_username:  xpcoffee
linkdin_username: emerickbosch

# Build config
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed