# Overall config
title: xpcoffee
email: xpc.dev@gmail.com
description: >- 
  ☕ ⌨️ ⚙️
baseurl: ""
url: "https://xpcoffee.github.io"
twitter_username: explodedcoffee
github_username:  xpcoffee
linkdin_username: emerickbosch

# Build config
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed