# Instructions for AWS Codebuild
version: 0.2
env:
  variables:
    S3_BUCKET_NAME: "emerickbosch.com"

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run deploy
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: yes
