# Instructions for AWS Codebuild
version: 0.1
phases:
  install:
    commands:
      - ‘npm install -g gatsby’
  pre_build:
    commands:
      - ‘npm install’
  build:
    commands:
      - ‘npm run build’
  post_build:
    commands:
      - ‘npm run deploy’
artifacts:
  base-directory: public
  files:
    - ‘**/*’
  discard-paths: yes
